"""Initial schema

Revision ID: 5311ba30791f
Revises: 
Create Date: 2026-07-14 23:50:02.399216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5311ba30791f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('logical_path', sa.String(), nullable=False),
    sa.Column('thumbnail_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('state_status', sa.String(length=50), nullable=False),
    sa.Column('state_progress_percent', sa.Float(), nullable=False),
    sa.Column('state_current_stage', sa.String(), nullable=True),
    sa.Column('state_error_message', sa.String(), nullable=True),
    sa.Column('state_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_state_status'), 'videos', ['state_status'], unique=False)
    op.create_table('scenes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('seconds_start', sa.Float(), nullable=False),
    sa.Column('seconds_end', sa.Float(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('thumbnail_path', sa.String(), nullable=True),
    sa.Column('transcript', sa.String(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('objects', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('activities', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('colors', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('ocr_text', sa.String(), nullable=True),
    sa.Column('ai_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenes_video_id'), 'scenes', ['video_id'], unique=False)
    op.create_table('captions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scene_id', sa.UUID(), nullable=False),
    sa.Column('tone', sa.String(length=50), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_captions_scene_id'), 'captions', ['scene_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_captions_scene_id'), table_name='captions')
    op.drop_table('captions')
    op.drop_index(op.f('ix_scenes_video_id'), table_name='scenes')
    op.drop_table('scenes')
    op.drop_index(op.f('ix_videos_state_status'), table_name='videos')
    op.drop_table('videos')
    # ### end Alembic commands ###
