"""
Authentication API schemas — Pydantic request/response models.

Rules:
  * These are the ONLY models that touch FastAPI/Pydantic.
  * Domain dataclasses and DTOs are never exposed directly.
  * Schemas wrap the AuthenticationApiService DTOs.
"""
from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Literal, Optional

from pydantic import BaseModel, EmailStr, Field, field_validator


# ---------------------------------------------------------------------------
# ── Shared primitives ────────────────────────────────────────────────────────
# ---------------------------------------------------------------------------

class ApiErrorSchema(BaseModel):
    code: str = Field(..., examples=["INVALID_CREDENTIALS"])
    message: str = Field(..., examples=["Invalid credentials."])
    details: Dict[str, Any] = Field(default_factory=dict)


class IdentitySchema(BaseModel):
    provider: str = Field(..., examples=["oauth"])
    oauth_provider: Optional[str] = Field(None, examples=["google"])
    provider_id: str
    linked_at: datetime

    model_config = {"from_attributes": True}


class UserSchema(BaseModel):
    user_id: str
    email: str
    username: str
    display_name: Optional[str] = None
    avatar_url: Optional[str] = None
    role: str
    status: str
    verified: bool
    identities: List[IdentitySchema] = []

    model_config = {"from_attributes": True}


class TokenSchema(BaseModel):
    access_token: str
    token_type: str = "Bearer"
    expires_in: Optional[int] = None
    refresh_token: Optional[str] = None


class SessionSchema(BaseModel):
    session_id: str
    user_id: str
    created_at: datetime


# ---------------------------------------------------------------------------
# ── Request bodies ───────────────────────────────────────────────────────────
# ---------------------------------------------------------------------------

class RegisterRequest(BaseModel):
    email: EmailStr = Field(..., examples=["user@example.com"])
    username: str = Field(..., min_length=3, max_length=50, examples=["johndoe"])
    password: str = Field(..., min_length=8, max_length=128, examples=["Str0ng!Pass"])

    model_config = {
        "json_schema_extra": {
            "example": {"email": "user@example.com", "username": "johndoe", "password": "Str0ng!Pass"}
        }
    }


class LoginRequest(BaseModel):
    email: EmailStr = Field(..., examples=["user@example.com"])
    password: str = Field(..., min_length=1, examples=["Str0ng!Pass"])

    model_config = {
        "json_schema_extra": {
            "example": {"email": "user@example.com", "password": "Str0ng!Pass"}
        }
    }


class LogoutRequest(BaseModel):
    session_id: Optional[str] = Field(None, examples=["sess-abc123"])


class RefreshRequest(BaseModel):
    session_id: Optional[str] = Field(None, examples=["sess-abc123"])


class OAuthBeginRequest(BaseModel):
    state: str = Field(..., min_length=8, description="CSRF-protection state token generated by the client.", examples=["random-opaque-state-string"])
    redirect_uri: str = Field(..., examples=["https://app.example.com/auth/callback"])


class OAuthCallbackRequest(BaseModel):
    code: str = Field(..., description="Authorization code returned by the provider.")
    state: str = Field(..., description="State echoed back by the provider (must match original).")
    redirect_uri: str = Field(..., examples=["https://app.example.com/auth/callback"])


class LinkIdentityRequest(BaseModel):
    provider: str = Field(..., description="OAuth provider slug.", examples=["google"])
    code: str = Field(..., description="Authorization code from the provider.")
    redirect_uri: str


# ---------------------------------------------------------------------------
# ── Response envelopes ───────────────────────────────────────────────────────
# ---------------------------------------------------------------------------

class RegisterResponse(BaseModel):
    success: bool
    user: Optional[UserSchema] = None
    requires_verification: bool = False
    error: Optional[ApiErrorSchema] = None


class LoginResponse(BaseModel):
    success: bool
    user: Optional[UserSchema] = None
    tokens: Optional[TokenSchema] = None
    session: Optional[SessionSchema] = None
    error: Optional[ApiErrorSchema] = None


class LogoutResponse(BaseModel):
    success: bool
    error: Optional[ApiErrorSchema] = None


class RefreshResponse(BaseModel):
    success: bool
    tokens: Optional[TokenSchema] = None
    session: Optional[SessionSchema] = None
    error: Optional[ApiErrorSchema] = None


class OAuthBeginResponse(BaseModel):
    success: bool
    authorization_url: Optional[str] = None
    error: Optional[ApiErrorSchema] = None


class OAuthCallbackResponse(BaseModel):
    success: bool
    user: Optional[UserSchema] = None
    tokens: Optional[TokenSchema] = None
    session: Optional[SessionSchema] = None
    is_new_user: bool = False
    error: Optional[ApiErrorSchema] = None


class IdentityLinkResponse(BaseModel):
    success: bool
    user: Optional[UserSchema] = None
    error: Optional[ApiErrorSchema] = None


class MeResponse(BaseModel):
    user: UserSchema


class ValidateResponse(BaseModel):
    success: bool
    user: Optional[UserSchema] = None
    token_claims: Optional[Dict[str, Any]] = None
    error: Optional[ApiErrorSchema] = None
